language: go

go:
  - "1.15"
  - "1.16"

install:
  - go get github.com/mattn/goveralls
  - make setup

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email:
    on_success: change
    on_failure: change
